/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.office.actionform;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-11-2006
 * 
 * XDoclet definition:
 * @struts.form name="mailform"
 */
public class MailForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** mailid property */
	private int mailid;
	
	/** geter property */
	private String geter;

	/** mark property */
	private String mark;

	/** s_date property */
	private String stime;

	/** sender property */
	private String sender;

	/** content property */
	private String content;

	/** subject property */
	private String subject;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the geter.
	 * @return String
	 */
	public String getGeter() {
		return geter;
	}

	/** 
	 * Set the geter.
	 * @param geter The geter to set
	 */
	public void setGeter(String geter) {
		this.geter = geter;
	}
	
	/** 
	 * Returns the mailid.
	 * @return int
	 */
	public int getMailid() {
		return mailid;
	}

	/** 
	 * Set the mailid.
	 * @param mailid The mailid to set
	 */
	public void setMailid(int mailid) {
		this.mailid = mailid;
	}

	/** 
	 * Returns the mark.
	 * @return String
	 */
	public String getMark() {
		return mark;
	}

	/** 
	 * Set the mark.
	 * @param mark The mark to set
	 */
	public void setMark(String mark) {
		this.mark = mark;
	}

	/** 
	 * Returns the s_date.
	 * @return String
	 */
	public String getStime() {
		return stime;
	}

	/** 
	 * Set the s_date.
	 * @param s_date The s_date to set
	 */
	public void setStime(String stime) {
		this.stime = stime;
	}

	/** 
	 * Returns the sender.
	 * @return String
	 */
	public String getSender() {
		return sender;
	}

	/** 
	 * Set the sender.
	 * @param sender The sender to set
	 */
	public void setSender(String sender) {
		this.sender = sender;
	}

	/** 
	 * Returns the content.
	 * @return String
	 */
	public String getContent() {
		return content;
	}

	/** 
	 * Set the content.
	 * @param content The content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/** 
	 * Returns the subject.
	 * @return String
	 */
	public String getSubject() {
		return subject;
	}

	/** 
	 * Set the subject.
	 * @param subject The subject to set
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}
	
	public void clear(){
       mailid=0;
       geter="";
       mark="";
       stime="";
       sender="";
       content="";
       subject="";
	}
}