/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.office.actionform;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-11-2006
 * 
 * XDoclet definition:
 * @struts.form name="moneythingform"
 */
public class MoneyThingForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** thingid property */
	private int thingid;

	
	/** type property */
	private String type;

	/** branch property */
	private String buybranch;

	/** model property */
	private String model;

	/** cost property */
	private String cost;

	/** buydate property */
	private String buytime;

	/** number property */
	private String number;
	
	public MoneyThingForm(){}

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	
	/** 
	 * Returns the thingid.
	 * @return String
	 */
	public int getThingid() {
		return thingid;
	}

	/** 
	 * Set the thingid.
	 * @param thingid The thingid to set
	 */
	public void setThingid(int thingid) {
		this.thingid = thingid;
	}
	
	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the branch.
	 * @return String
	 */
	public String getBuybranch() {
		return buybranch;
	}

	/** 
	 * Set the branch.
	 * @param branch The branch to set
	 */
	public void setBuybranch(String branch) {
		this.buybranch = branch;
	}

	/** 
	 * Returns the model.
	 * @return String
	 */
	public String getModel() {
		return model;
	}

	/** 
	 * Set the model.
	 * @param model The model to set
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/** 
	 * Returns the cost.
	 * @return String
	 */
	public String getCost() {
		return cost;
	}

	/** 
	 * Set the cost.
	 * @param cost The cost to set
	 */
	public void setCost(String cost) {
		this.cost = cost;
	}

	/** 
	 * Returns the buydate.
	 * @return String
	 */
	public String getBuytime() {
		return buytime;
	}

	/** 
	 * Set the buydate.
	 * @param buydate The buydate to set
	 */
	public void setBuytime(String buydate) {
		this.buytime = buydate;
	}

	/** 
	 * Returns the number.
	 * @return String
	 */
	public String getNumber() {
		return number;
	}

	/** 
	 * Set the number.
	 * @param number The number to set
	 */
	public void setNumber(String number) {
		this.number = number;
	}
	
	public void clear(){
		thingid=0;
        type="";
        buybranch="";
        model="";
		cost="";
        buytime="";
		number="";
	}
}