/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.office.actionform;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-11-2006
 * 
 * XDoclet definition:
 * @struts.form name="moneycarform"
 */
public class MoneyCarForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** car property */
	private int carid;
	
	/** info property */
	private String info;

	/** fdnumber property */
	private String fdj;

	/** model property */
	private String model;

	/** status property */
	private String status;

	/** bxinfo property */
	private String bxinfo;

	/** driver property */
	private String driver;

	/** njinfo property */
	private String njinfo;

	/** makeuser property */
	private String maker;

	/** buydate property */
	private String buytime;

	/** number property */
	private String number;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the carid.
	 * @return int
	 */
	public int getCarid() {
		return carid;
	}

	/** 
	 * Set the carid.
	 * @param carid The carid to set
	 */
	public void setCarid(int carid) {
		this.carid = carid;
	}
	
	/** 
	 * Returns the info.
	 * @return String
	 */
	public String getInfo() {
		return info;
	}

	/** 
	 * Set the info.
	 * @param info The info to set
	 */
	public void setInfo(String info) {
		this.info = info;
	}

	/** 
	 * Returns the fdnumber.
	 * @return String
	 */
	public String getFdj() {
		return fdj;
	}

	/** 
	 * Set the fdnumber.
	 * @param fdnumber The fdnumber to set
	 */
	public void setFdj(String fdnumber) {
		this.fdj = fdnumber;
	}

	/** 
	 * Returns the model.
	 * @return String
	 */
	public String getModel() {
		return model;
	}

	/** 
	 * Set the model.
	 * @param model The model to set
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/** 
	 * Returns the status.
	 * @return String
	 */
	public String getStatus() {
		return status;
	}

	/** 
	 * Set the status.
	 * @param status The status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/** 
	 * Returns the bxinfo.
	 * @return String
	 */
	public String getBxinfo() {
		return bxinfo;
	}

	/** 
	 * Set the bxinfo.
	 * @param bxinfo The bxinfo to set
	 */
	public void setBxinfo(String bxinfo) {
		this.bxinfo = bxinfo;
	}

	/** 
	 * Returns the driver.
	 * @return String
	 */
	public String getDriver() {
		return driver;
	}

	/** 
	 * Set the driver.
	 * @param driver The driver to set
	 */
	public void setDriver(String driver) {
		this.driver = driver;
	}

	/** 
	 * Returns the njinfo.
	 * @return String
	 */
	public String getNjinfo() {
		return njinfo;
	}

	/** 
	 * Set the njinfo.
	 * @param njinfo The njinfo to set
	 */
	public void setNjinfo(String njinfo) {
		this.njinfo = njinfo;
	}

	/** 
	 * Returns the makeuser.
	 * @return String
	 */
	public String getMaker() {
		return maker;
	}

	/** 
	 * Set the makeuser.
	 * @param makeuser The makeuser to set
	 */
	public void setMaker(String makeuser) {
		this.maker = makeuser;
	}

	/** 
	 * Returns the buydate.
	 * @return String
	 */
	public String getBuytime() {
		return buytime;
	}

	/** 
	 * Set the buydate.
	 * @param buydate The buydate to set
	 */
	public void setBuytime(String buydate) {
		this.buytime = buydate;
	}

	/** 
	 * Returns the number.
	 * @return String
	 */
	public String getNumber() {
		return number;
	}

	/** 
	 * Set the number.
	 * @param number The number to set
	 */
	public void setNumber(String number) {
		this.number = number;
	}

    public void clear(){
      info="";
      fdj="";   	
      model="";   	
      status="";   	
      bxinfo="";
      driver="";
      njinfo="";
      maker="";
      buytime="";
      number="";
    }
}